# Notification Delivery Configuration for the Cuculi Nudge System
channels:
  push:
    provider: "onesignal"
    enabled: true
    config:
      app_id: "${ONESIGNAL_APP_ID}"
      api_key: "${ONESIGNAL_API_KEY}"
      timeout: 10
      retry_attempts: 3
    formatting:
      max_title_length: 50
      max_body_length: 160
      supports_emoji: true
      supports_rich_media: true
    delivery_options:
      immediate: true
      scheduled: true
      timezone_aware: true
      sound_enabled: true
      badge_enabled: true

  sms:
    provider: "twilio"
    enabled: true
    config:
      account_sid: "${TWILIO_ACCOUNT_SID}"
      auth_token: "${TWILIO_AUTH_TOKEN}"
      from_number: "${TWILIO_PHONE_NUMBER}"
      timeout: 15
      retry_attempts: 2
    formatting:
      max_length: 160
      supports_emoji: false
      supports_links: true
    delivery_options:
      delivery_receipts: true
      link_tracking: true
      opt_out_handling: true

  email:
    provider: "mailchimp"
    enabled: true
    config:
      api_key: "${MAILCHIMP_API_KEY}"
      list_id: "${MAILCHIMP_LIST_ID}"
      timeout: 20
      retry_attempts: 3
    formatting:
      max_subject_length: 78
      supports_html: true
      supports_attachments: false
    delivery_options:
      open_tracking: true
      click_tracking: true
      unsubscribe_link: true
      template_id: "cuculi_event_notification"

# Channel Selection Rules
selection_rules:
  user_preference_priority: true
  fallback_chain: ["push", "sms", "email"]
  time_sensitive:
    immediate: ["push", "sms"]
    scheduled: ["email", "push"]
  user_engagement_level:
    high: ["push", "sms"]
    medium: ["push", "email"]
    low: ["email", "sms"]
